server:
  port: 8083
  servlet:
    context-path: /notification

spring:
  application:
    name: notification
  datasource:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:anhphamle2002@gmail.com}
    password: ${MAIL_PASSWORD:vjca niuf iyrl pfzy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  # config connection with rabbitMQ broker
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# config exchange for producer
rabbitmq:
  seminar:
    exchange: seminar.ticket-booked.direct.exchange
    routing-key: seminar.ticket-booked
    queue: seminar.ticket-booked.notification.queue
  user:
    exchange: user.registered.direct.exchange
    routing-key: user.registered
    queue: user.registered.notification.queue



  # OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  show-actuator: true
  packages-to-scan: org.swd392.notification
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  writer-with-default-pretty-printer: true



# config actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints over HTTP
  endpoint:
    shutdown:
      access: unrestricted  # Allow unrestricted access to the shutdown endpoint
      # NOTE: only use this shutdown endpoint config in dev env
  info:
    env:
      enabled: true         # show info env in /actuator/info


# config eureka client
eureka:
  instance:
    prefer-ip-address: true # Tells Eureka to use the IP address instead of the hostname when registering the service. Because there is no DNS locally or in Docker.
  client:
    enabled: false
    fetch-registry: false
    register-with-eureka: false



# info of Eureka client on the Eureka Server Dashboard
info:
  app:
    name: ${spring.application.name}
    description: "This is notification service in Career Path Personality Assessment System"

logging:
  level:
    org.springframework.mail: DEBUG
    org.swd392.notification: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    feign: DEBUG
