server:
  port: 8072 # Port for the API Gateway service

spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable discovery of services registered with Eureka
          lowerCaseServiceId: true  # Use lower case service IDs when routing


# config actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints over HTTP
  endpoint:
    gateway:
      access: unrestricted  # Enable the gateway actuator endpoint


  info:
    env:
      enabled: true         # show info env in /actuator/info


# config eureka client
eureka:
  instance:
    prefer-ip-address: true # Tells Eureka to use the IP address instead of the hostname when registering the service. Because there is no DNS locally or in Docker.
  client:
    fetch-registry: true # Tells eureka client to fetch the registry from the Eureka server
    register-with-eureka: true # tells eureka client to register itself with the Eureka server
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL of the Eureka server, this url can be hardcoded because it has only 1 Eureka server in the system


# info of Eureka client on the Eureka Server Dashboard
info:
  app:
    name: ${spring.application.name}
    description: "This is api gateway server in Career Path Personality Assessment System"
