server:
  port: 8080
  servlet:
    context-path: /user

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:userDB}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true  # tell Hibernate to create schema before SQL init
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql  # Location of the data.sql file to initialize the database
  mail:
    host: smtp.gmail.com
    port: 587
    username: testpersonality134@gmail.com
    password: okjl jixz grdk qcuh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  # config connection with rabbitMQ broker
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

  # config exchange for producer
rabbitmq:
  exchange: user.registered.direct.exchange
  routing-key: user.registered


# config actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints over HTTP
  endpoint:
    shutdown:
      access: unrestricted  # Allow unrestricted access to the shutdown endpoint
      # NOTE: only use this shutdown endpoint config in dev env
  info:
    env:
      enabled: true         # show info env in /actuator/info


# config eureka client
eureka:
  instance:
    prefer-ip-address: true # Tells Eureka to use the IP address instead of the hostname when registering the service. Because there is no DNS locally or in Docker.
  client:
    fetch-registry: true # Tells eureka client to fetch the registry from the Eureka server
    register-with-eureka: true # tells eureka client to register itself with the Eureka server
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

# info of Eureka client on the Eureka Server Dashboard
info:
  app:
    name: ${spring.application.name}
    description: "This is quiz service in Career Path Personality Assessment System"


logging:
  level:
    org.springframework.security: TRACE


springdoc:
  swagger-ui:
    path: /swagger-ui.html

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8083/notification}


