CREATE TYPE option_text_enum AS ENUM ('AGREE', 'DISAGREE', 'NEUTRAL');

CREATE TYPE dimension_enum AS ENUM (
  'EXTRAVERSION_INTROVERSION',
  'JUDGING_PERCEIVING',
  'SENSING_INTUITION',
  'THINKING_FEELING'
);

CREATE TYPE mbti_enum AS ENUM (
  'ENFJ','ENFP','ENTJ','ENTP',
  'ESFJ','ESFP','ESTJ','ESTP',
  'INFJ','INFP','INTJ','INTP',
  'ISFJ','ISFP','ISTJ','ISTP'
);

-- Check if tables exist before creating them
DO $$ 
BEGIN
    -- Create options table if not exists
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'options') THEN
        CREATE TABLE options (
            option_id SERIAL PRIMARY KEY,
            option_text TEXT,
            score_delta VARCHAR(50)
        );
    END IF;

    -- Create questions table if not exists
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'questions') THEN
        CREATE TABLE questions (
            question_id SERIAL PRIMARY KEY,
            text TEXT NOT NULL,
            dimension VARCHAR(50) NOT NULL,
            order_number INTEGER NOT NULL
        );
    END IF;

    -- Add more table creation statements as needed
END $$;

create table results (
    result_id integer generated by default as identity, 
    mbit_type mbti_enum not null, 
    result_json TEXT not null, 
    primary key (result_id)
)